# The name of experiment
experiment: imgnet

# The name of job
name: timm-effnet

# The name of vm type
vm: azure-80gb-a100-2g-eastus2

# The number of GPU devices
num_devices: 2

# Configure your job!
job_setting:
  type: custom

  # Docker config
  docker:
    # Docker image you want to use in the job
    image: friendliai/periflow:sdk
    # Bash shell command to run the job
    command: >
      cd /workspace/imagenet && pip install -r requirements.txt && torchrun --nnodes $NUM_NODES --node_rank $NODE_RANK --master_addr $MASTER_ADDR --master_port 6000 --nproc_per_node $NPROC_PER_NODE train.py \
        /workspace/data/reduced-tiny-imagenet \
        --dataset reduced-tiny-imagenet \
        --model efficientnet_b0 \
        --epochs 50 \
        --log-interval 50 \
        --output /workspace/ckpt
  # Path to mount your workspace volume
  workspace:
    mount_path: /workspace

# Checkpoint config
checkpoint:
  # Input checkpoint
  # (Add `--initial-checkpoint` to specify checkpoint directory for model initialization,
  # and --resume to resume entire training states.)
  # input:
  #   id: ab48fcbf-cc1b-4493-8323-e9c6ebb8ee76
  #   mount_path: /workspace/ckpt
  # Path to output checkpoint
  output_checkpoint_dir: /workspace/ckpt

# Dataset config
data:
  name: reduced-tiny-imagenet
  mount_path: /workspace/data
