# The name of experiment
experiment: huggingface-sum

# The name of job
name: sum-bart

# The name of vm type
vm: azure-80gb-a100-2g-eastus2

# The number of GPU devices
num_devices: 2

# Configure your job!
job_setting:
  type: custom

  # Docker config
  docker:
    # Docker image you want to use in the job
    image: friendliai/periflow:sdk
    # Bash shell command to run the job
    command: >
      cd /workspace/bart_finetuning && pip install -r requirements.txt && torchrun --nnodes $NUM_NODES --node_rank $NODE_RANK --master_addr $MASTER_ADDR --master_port 6000 --nproc_per_node $NPROC_PER_NODE run_summarization.py \
        --model_name_or_path facebook/bart-base \
        --dataset_name cnn_dailymail \
        --dataset_config "3.0.0" \
        --cache_dir /workspace/data/cnn_dailymail \
        --per_device_train_batch_size 16 \
        --per_device_eval_batch_size 16 \
        --do_train \
        --do_eval \
        --output_dir /workspace/ckpt
  # Path to mount your workspace volume
  workspace:
    mount_path: /workspace

# Checkpoint config
checkpoint:
  # Input checkpoint
  # input:
  #   id: 687eb085-bac6-4e6c-af95-da1ab047e3d3
  #   mount_path: /workspace/ckpt
  # Path to output checkpoint
  output_checkpoint_dir: /workspace/ckpt

# Dataset config
data:
  name: cnn_dailymail
  mount_path: /workspace/data
